spring:
  profiles:
    active: gmail
  config:
    name: application, application-gmail
     
  application:
    name: email-ms
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          
server:
  port: 0
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true
    
      