# Configurações específicas para o perfil Gmail
spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME_GMAIL}
    password: ${MAIL_PASSWORD_GMAIL}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
